server.port=8086

spring.application.name=mscv-stats

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka Client
eureka.client.serviceUrl.defaultZone=${EUREKA_URL}
eureka.instance.preferIpAddress=true

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# JWT Configuration Properties
authorization.jwt.expiration.days=7
authorization.jwt.secret=AventuraPeSecureTokenKey2025WithStrongSecurityRequiredFor256Bits

# Security configurations
spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWK_SET_URI}

# Feign Client URLs for service communication
feign.comments-service.url=${COMMENTS_SERVICE_URL}
feign.post-service.url=${POST_SERVICE_URL}