server.port=8080

spring.application.name=mscv-gateway
spring.cloud.gateway.discovery.locator.enabled=true

# Route for authentication
spring.cloud.gateway.routes[0].id=iam-auth
spring.cloud.gateway.routes[0].uri=${IAM_SERVICE_URL}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/authentication/**

# Route for roles
spring.cloud.gateway.routes[1].id=iam-roles
spring.cloud.gateway.routes[1].uri=${IAM_SERVICE_URL}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/roles/**

# Route for users
spring.cloud.gateway.routes[2].id=iam-users
spring.cloud.gateway.routes[2].uri=${IAM_SERVICE_URL}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/users/**

# Route for profiles
spring.cloud.gateway.routes[3].id=profile-service
spring.cloud.gateway.routes[3].uri=${PROFILE_SERVICE_URL}
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/profiles/**

# Route for publications (post-service)
spring.cloud.gateway.routes[4].id=post-publications
spring.cloud.gateway.routes[4].uri=${POST_SERVICE_URL}
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/publications/**

# Route for comments
spring.cloud.gateway.routes[5].id=comments-service
spring.cloud.gateway.routes[5].uri=${COMMENTS_SERVICE_URL}
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/comments/**

# Route for favorites
spring.cloud.gateway.routes[6].id=favorites-service
spring.cloud.gateway.routes[6].uri=${FAVORITES_SERVICE_URL}
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/v1/favorites/**

# Route for statistics service
spring.cloud.gateway.routes[7].id=stats-service
spring.cloud.gateway.routes[7].uri=${STATS_SERVICE_URL}
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/v1/stats/**

#Route for categories
spring.cloud.gateway.routes[8].id=categories
spring.cloud.gateway.routes[8].uri=${CATEGORIES_SERVICE_URL}
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/v1/categories/**

# Route for publication categories
spring.cloud.gateway.routes[9].id=post-categories
spring.cloud.gateway.routes[9].uri=${CATEGORIES_SERVICE_URL}
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/v1/publication-categories/**

# Route for category subscriptions
spring.cloud.gateway.routes[10].id=categories-suscriptions
spring.cloud.gateway.routes[10].uri=${CATEGORIES_SERVICE_URL}
spring.cloud.gateway.routes[10].predicates[0]=Path=/api/v1/category-subscriptions/**

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=${ALLOWED_ORIGINS}
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

