server.port=8087
spring.application.name=mscv-subscriptions

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

#Eureka configuration
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# JWT Configuration Properties
authorization.jwt.expiration.days=7
authorization.jwt.secret=AventuraPeSecureTokenKey2025WithStrongSecurityRequiredFor256Bits

# Enable snake case for Hibernate naming strategy
spring.jpa.hibernate.naming.physical-strategy=com.aventurape.subscriptions_service.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

# Documentation properties
documentation.application.description=@project.description@
documentation.application.version=@project.version@

# RabbitMQ Configuration
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

# Feign Configuration
subscriptions-service.url=${SUBSCRIPTIONS_SERVICE_URL}

