spring.application.name=mscv-comments

spring.config.import=optional:configserver:http://localhost:8888

# Logging Configuration
logging.level.com.aventurape.comments_service.infrastructure.security=DEBUG
logging.level.com.aventurape.comments_service.interfaces.rest=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# Database Configuration
# spring.datasource.hikari.auto-commit=false

# Transaction Management
# spring.jpa.properties.hibernate.connection.autocommit=false
# spring.jpa.properties.hibernate.current_session_context_class=thread


# Logging Configuration
logging.level.com.aventurape.post_service.infrastructure.security=INFO 

# PostgreSQL LOB Configuration
spring.jpa.properties.hibernate.connection.provider_disables_autocommit=true 