spring.application.name=mscv-eureka
spring.config.import=optional:configserver:http://config-service:8888
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.hostname=localhost